### ISSUE TITLE
Using the library without cuda

### ISSUE THREAD

**Issue by NicoClinco** [NVIDIA/TorchFort#16]
Hello, i was wondering if it is possibile to have a version of this library that run without the cuda support since i want to use the library on cpu.

Thanks in advance for the answer
Nico

**Comment by azrael417** [comment]
Hello Nico, 

thank you for your interest in TorchFort. We are currently looking at CPU support and while I think that you need to have the CUDA SDK to compile the library, running on CPU is supported if the library is compiled with GNU. But let me check that in detail and get back to you. Sorry for the delay.

Best and thanks
Thorsten

**Comment by NicoClinco** [comment]
Hi,
thank you so much for your work, i will test the functionalities soon.
Best wishes,
Nicola

Il giorno gio 5 set 2024 alle ore 09:50 Thorsten Kurth <
***@***.***> ha scritto:
