### ISSUE TITLE
potential do operator missing

### ISSUE THREAD

**Issue by Kait0** [NVIDIA/TorchFort#30]
While going through the code it looked to me that there is a do operator missing [here](https://github.com/NVIDIA/TorchFort/blob/b7377d0b3824b7e9a66c1b2773dd89925c4e45d2/src/csrc/include/internal/defines.h#L71).
at least the other similar blocks have it: [here](https://github.com/NVIDIA/TorchFort/blob/b7377d0b3824b7e9a66c1b2773dd89925c4e45d2/src/csrc/include/internal/defines.h#L53)

Not sure what the point of do {...} while (false) is. I guess it is a technique to write a bunch of code in 1 line?

**Comment by azrael417** [comment]
Hello Kait, 

I think you are right. Yes, the do-whiles are basically just to write the macros in a way to make code look more uniform, you can use them as other functions. Please check this https://stackoverflow.com/questions/1067226/c-multi-line-macro-do-while0-vs-scope-block for more info. I will fix the issue, thank you very much for catching this.

Best and thanks
